# Generated by Django 4.1.7 on 2023-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0005_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('cv', models.CharField(max_length=100)),
            ],
        ),
    ]
