# Generated by Django 4.1.7 on 2023-03-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
